[package]
name = "controlbits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
permutation = "0.4.1"
itertools = "0.11.0"
